[project]
name = "diffsmile"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "arrow>=1.4.0",
    "connectorx>=0.4.4",
    "fastexcel>=0.18.0",
    "ipykernel>=7.2.0",
    "jaxtyping>=0.3.3",
    "lightning>=2.6.1",
    "matplotlib>=3.10.8",
    "numpy>=2.3.3",
    "optuna>=4.7.0",
    "optuna-integration[pytorch-lightning]>=4.7.0",
    "pandas>=3.0.1",
    "polars>=1.34.0",
    "pyarrow>=23.0.1",
    "pydantic>=2.12.5",
    "scikit-learn>=1.8.0",
    "scipy>=1.16.2",
    "seaborn>=0.13.2",
    "torch>=2.9.0",
    "tqdm>=4.67.1",
    "yfinance>=1.0",
]

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = ""

[dependency-groups]
dev = [
    "basedpyright>=1.31.6",
    "ruff>=0.13.3",
    "notebook>=7.4.7",
    "jupyterlab-lsp>=5.2.0",
    "ty>=0.0.26",
]

[tool.basedpyright]
reportUnannotatedClassAttribute=false
reportUnusedCallResult=false
reportUninitializedInstanceVariable=false
reportAny=false
ignore = ["QuantLib", "torch"]

[tool.ruff]
line-length = 130
fix = true

exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    "__init__.py",
]

target-version = "py312"

extend-exclude = [".venv"]

# See: https://github.com/charliermarsh/ruff#supported-rules
[tool.ruff.lint]
select = [
    "F", # Pyflakes
    "E", # pycodestyle Error
    "W", # pycodestyle Warning
    "C90", # mccabe
    "I", # isort
    "D", # pydocstyle
    "UP", # pyupgrade
    "N", # pep8-naming
    "YTT", # flake8-2020
    "ASYNC", # flake8-async
    "ANN", # flake8-annotations
    "S", # flake8-bandit
    "BLE", # flake8-blind-except
    "FBT", # flake8-boolean-trap
    "B", # flake8-bugbear
    "A", # flake8-builtins
    "C4", # flake8-comprehensions
    "T10", # flake8-debugger
    "DJ", # flake8-django
    "EM", # flake8-errmsg
    "ISC", # flake8-implicit-str-concat
    "ICN", # flake8-import-conventions
    "T20", # flake8-print
    "PYI", # flake8-pyi
    "R", # refactor
    "Q", # flake8-quotes
    "RET", # flake8-return
    "SLF", # flake8-self
    "PT", # flake8-pytest-style
    "SIM", # flake8-simplify
    "TID", # flake8-tidy-imports
    "ARG", # flake8-unused-arguments
    "DTZ", # flake8-datetimez
    "ERA", # eradicate
    "PD", # pandas-vet
    "PGH", # pygrep-hooks
    "PLC", # Pylint Convention
    "PLE", # Pylint Error
    "PLR", # Pylint Refactor
    "PLW", # Pylint Warning
    "PIE", # flake8-pie
    "COM", # flake8-commas
    "INP", # flake8-no-pep420
    "EXE", # flake8-executable
    "TCH", # flake8-type-checking
    "ARG", # flake8-unused-arguments
    "TRY", # tryceratops
    "PTH", # flake8-use-pathlib
    "RUF", # Ruff-specific rules
    "RSE", # flake8-raise
    "SLOT", # flake8-slots
    "TD", # flake8-todos
    "FLY", # flynt
    "NPY", # NumPy-specific rules
    "PERF", # Perflint
    "G", # flake8-logging-format
    "PL", # Pylint
    "FURB", # refurb
]

ignore = [
    "D100", # Missing docstring in public module
    "D101", # Missing docstring in public class
    "D102", # Missing docstring in public method
    "D103", # Missing docstring in public function
    "D104", # Missing docstring in public package
    "D105", # Missing docstring in magic method
    "D106", # Missing docstring in public nested class
    "D107", # Missing docstring in __init__
    "TD003", # Missing issue link on the line following this TODORuffTD003
    "D211", # No blank lines allowed before class docstring
    "D213", # Multi-line docstring summary should start at the second line
    "G004", # Logging statement uses string formatting
    "D203", # 1 blank line required before class docstring
    "COM812", # Trailing comma missing (conflicts with formatter)
    "DTZ011", # Use `datetime.datetime.now(tz=...).date()` instead
    "DTZ005", # datetime.datetime.now()` called without a `tz` argument
    "S101", #Use of `assert` detected
    "T201", # print statement found
    "F722", # Syntax error in forward annotation: Unexpected token at the end of an expression
    "N806", #Variable `X` in function should be lowercase
    "N815", #Variable `sqrt_one_minus_alphas_cumprod_T2` in class scope should not be mixedCase
    "N803", #Argument name `T1` should be lowercase
]

unfixable = ["F401"]
[tool.ruff.lint.isort]
required-imports = ["from __future__ import annotations"]
